BLOODWOLF333/Brutal-Doom-Community-Expansion

ArchVile.txt
Baron.txt
Cacodemo.txt
DyingGuys.txt
ExpansionChangelog.txt
Imps.txt
Juggernaut.txt
Knight.txt
LABGUY.txt
Mancubus.txt
Mastermind.txt
Spiders.txt
Spiders2.txt
Volcabus.txt

Changed the flags to +SOLID for the various dying guys to normalize all of their behavior

Non-Solid DyingGuys

---

Axe.txt
BFG.txt
BFG10k.txt
ExpansionChangelog.txt
FlameCannon.txt
Flamethrower.txt
Grenades.txt
HellishMissile.txt
Machinegun.txt
Melee.txt
Minigun.txt
Mp40.txt
NukeLauncher.txt
Saw.txt
Unmaker.txt

Queued Reloading Fix

---

MARINES.txt

Add DamageFactor "Trample" To Marine Actor

---

ChaingunMarine.txt
ExpansionChangelog.txt
PlasmagunMarine.txt
ShotgunMarine.txt

Fixed Friendly Marines DropItems

---

ExpansionChangelog.txt
MARINES.txt
Revolver.txt
Revolver2.txt
WeaponSpawners.txt

Created Revolver Spawner

---

Cyberdemon.txt
ExpansionChangelog.txt
Head_Sys.txt
SpecialDoom1Bosses.txt

Fixed E2M8 Cyberdemon Head Deaths

---

Cyberdemon.txt
EnemyTanks.txt
ExpansionChangelog.txt
Explosives.txt
Juggernaut.txt
Mastermind.txt
Tracers.txt

Fix Juggeranut and other boss monster in-fighting

---

DemonRunesPatch.txt
ExpansionChangelog.txt

Fix BaronPlayer Attacks

---

ExpansionChangelog.txt
Mummy.txt

Experiment-specific Obituary

---

DEFAULTWEAPON.txt
ExpansionChangelog.txt

Fix Weapon Disappearing

---

ExpansionChangelog.txt
MAPINFO.txt
Motherdemon.txt
SpecialDoom1Bosses.txt

Motherdemon Death and Level Endings

---

Baron.txt
Belphegor.txt
Cacodemo.txt
Demons.txt
ExpansionChangelog.txt
Imps.txt
Knight.txt
Revenant.txt

Sped-up Monster Fatalities

---

DyingGuys.txt
ExpansionChangelog.txt

Added -SOLID flag

---

Ammo.txt
ExpansionChangelog.txt
Imps.txt

Pistol ammo box pickup sound

---

BFG.txt
BFG10k.txt
DualMP40.txt
DualPistol.txt
DualPlasma.txt
DualRifle.txt
DualSMG.txt
ExpansionChangelog.txt
FlameCannon.txt
Flamethrower.txt
GrenadeLaunch.txt
HellishMissile.txt
Machinegun.txt
Minigun.txt
Mp40.txt
NukeLauncher.txt
Pistol.txt
Plasma.txt
Railgun.txt
Revolver.txt
Revolver2.txt
Rifle.txt
RocketLauncher.txt
SSG.txt
Saw.txt
Shotgun.txt
SubMachinegun.txt
Unmaker.txt

Added weapon spawners to Spawn states

---

ChaingunMarine.txt
ExpansionChangelog.txt
Tracers.txt

Fix MarineTracer

---

ExpansionChangelog.txt
Head_Sys.txt
Leg.txt

Set Damagefactor "Fire" to zero

---

DyingGuys.txt
ExpansionChangelog.txt

Non solid dying guys

---

DEFAULTWEAPON.txt
ExpansionChangelog.txt

Increase Flashlight Projectile Time

---

AssaultShotgun.txt
DualMP40.txt
DualPistol.txt
DualPlasma.txt
DualRifle.txt
DualSMG.txt
Mp40.txt
Pistol.txt
Plasma.txt
Railgun.txt
Rifle.txt
RocketLauncher.txt
Shotgun.txt
SubMachinegun.txt

Attempt to Fix Reloading Online

---

AssaultShotgun.txt
DualPistol.txt
DualRifle.txt
DualSMG.txt
ExpansionChangelog.txt
Mp40.txt
Pistol.txt
Rifle.txt
Shotgun.txt
SubMachinegun.txt

Fix TurboReload States

---

Ammo.txt
Baron.txt
ClassicWeapons.txt
DEFAULTWEAPON.txt
DyingGuys.txt
Head_Sys.txt
Leg.txt
PainElemental.txt
Player.txt
Revenant.txt
WeaponSpawners.txt

Update Classic Weapons

---

ExpansionChangelog.txt
Spiders2.txt

Arachontron2 Idle Fix

---

DEFAULTWEAPON.txt
ExpansionChangelog.txt

Already had +CLIENTSIDEONLY so also added +NONETID to hopefully fix the problem
Closes #119

Added +NONETID

---

CguyShield.txt
EvilMarineShield.txt
ExpansionChangelog.txt
Head_Sys.txt
NaziShield.txt
SguyShield.txt
Tracers.txt
ZmanShield.txt
ZombieCivilianShield.txt

Functional Meatshield Weapons

---

ExpansionChangelog.txt
Machinegun.txt

Add primaryfire check to ready state

---

AssaultShotgun.txt
BFG.txt
BFG10k.txt
ExpansionChangelog.txt
FlameCannon.txt
Flamethrower.txt
GrenadeLaunch.txt
Grenades.txt
HellishMissile.txt
Machinegun.txt
Minigun.txt
Mp40.txt
NukeLauncher.txt
Pistol.txt
Plasma.txt
Railgun.txt
Revolver.txt
Revolver2.txt
Rifle.txt
RocketLauncher.txt
SSG.txt
Shotgun.txt
SubMachinegun.txt
Unmaker.txt

Polished Sprinting States

---

ClassicWeapons.txt
ExpansionChangelog.txt

Add TryUse line to FlashOn state

---

MapSpecificDec.txt

Add +AMBUSH flag to SpecimenTank with an Experiment

---

ClassicWeapons.txt
DEFAULTWEAPON.txt
ExpansionChangelog.txt
Player.txt

Noticed weirdness with first person executions when the monster other than an Imp are against a wall

Fix First Person Executions

---

ClassicWeapons.txt
ExpansionChangelog.txt

Make Alerter Not Use Ammo

---

ClassicWeapons.txt
DEFAULTWEAPON.txt
ExpansionChangelog.txt

Added +PAINLESS flag to flashlight projectiles

---

DEFAULTWEAPON.txt
ExpansionChangelog.txt

Add flags to FlashlightAlerter

---

ClassicWeapons.txt
DEFAULTWEAPON.txt
ExpansionChangelog.txt

Fix flashlight states

---

AssaultShotgun.txt
DEFAULTWEAPON.txt
DualPistol.txt
DualPlasma.txt
DualRifle.txt
ExpansionChangelog.txt
Mp40.txt
Plasma.txt
Rifle.txt
RocketLauncher.txt
SubMachinegun.txt

Fix AutoReload Feature

---

Ammo.txt
ExpansionChangelog.txt
FlameCannon.txt
HellishMissile.txt
NukeLauncher.txt
WeaponSpawners.txt

Add Quiet flag to fake sprites

---

ArchVile.txt
Baron.txt
Cacodemo.txt
Comando.txt
Cyberdemon.txt
DemonRunesPatch.txt
Demons.txt
EEEVILLL.txt
ExpansionChangelog.txt
Imps.txt
Knight.txt
LABGUY.txt
LostSoul.txt
Mancubus.txt
Mastermind.txt
Motherdemon.txt
Mummy.txt
Nazis.txt
PainElemental.txt
Revenant.txt
Sergeants.txt
Spiders.txt
Ubersoldat.txt
Zombiemen.txt

Added the ExtremePunches and Fatality DamageFactors back in due to several complaints

Modify DamageFactors

---

ExpansionChangelog.txt
Melee.txt

Removed duplicate frame

---

ExpansionChangelog.txt
Melee.txt

Adjusted the A_SetAngle() lines

---

ExpansionChangelog.txt
Revenant.txt

Removed +NOTARGET

---

ExpansionChangelog.txt
Limbs.txt
Mancubus.txt
Revenant.txt

Radius, Height, and GoreSpawners

---

ExpansionChangelog.txt
LABGUY.txt
Revenant.txt

Adjust Melee Ranges

---

DEAD.txt
DyingGuys.txt
ExpansionChangelog.txt
Player.txt
Revenant.txt

Revenant Edits

---

ExpansionChangelog.txt
Limbs.txt
Player.txt
Revenant.txt

Fix HML Spawns

---

ClassicWeapons.txt
ExpansionChangelog.txt

Update Script Calls

---

ExpansionChangelog.txt
PainElemental.txt
Player.txt

Fix FatalizedPE actor

---

Comando.txt
Demons.txt
ExpansionChangelog.txt
Imps.txt
Sergeants.txt
VanillaMonsters.txt
Zombiemen.txt

Fix-up the vanilla monsters

---

ChaingunMarine.txt
ExpansionChangelog.txt
MARINES.txt
PlasmagunMarine.txt
ShotgunMarine.txt

Added missing ChangeFlag

---

EEEVILLL.txt
ExpansionChangelog.txt
Player.txt
Rifle.txt

Closes #232 
Adjusted Health, Speed, JumpHeight, created weapon-specific melee states and an airkick attack to EvilMarines.

#232 feature

---

Executions.txt

Yep I forgot to report this one the whole time, my bad

Fix shotgun guy's head effect for first person execution

---

LABGUY.txt
Sergeants.txt

After almost 20 hours I just found out this guy spawns an actor with his head remain intact, I feel like I bothered Wolf by sending a pull request when I missed something else related to it
Also thank you so much for putting me on the credits, man. I really appreciate that

Recorrected the decapitated one-leg sergeant

---

Imps.txt
Sergeants.txt
Zombiemen.txt

Just doing some playtesting again and found out the brutalized zombiemen, sergeants and imps spawned body parts that no longer belonged to their body
I also added a lil' addition for them

Changes to brutalized zombies and imps

---

LastStandMonsters.txt

They were all using a pistol and the emissions of the rifle single fire sound and case for it had been left unreplaced for years
Not really a bug or a glitch, it's kinda like an imperfection
Oh and btw, I'm back, Carr. I've been pretty busy with school and stuff

Using the right effects for last standers

---

Grenades.txt

If you equip hand grenades, having none will prevent you from sprinting, kicking, executing, taunting and saluting

I don't know if this is necessary to fix

---

Machinegun.txt
Minigun.txt
Mp40.txt
Railgun.txt
RocketLauncher.txt

Having no ammo on or unloaded certain weapons prevents you from doing execution

A little fix

---

Zombiemen.txt

Feels weird seeing him getting up and start running about on two upon getting burnt when he got one blown off

One leg burning zombieman

---

Axe.txt

Noticed that when you throw an axe, the token remains

Cutting Weapon token
